.\" Copyright (C) 1997 Red Hat Software, Inc.
.\"
.\" This is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH USERPASSWD 1 "17 October 1997" "Red Hat Software"
.SH NAME
userpasswd \- A graphical tool to allow users to change their passwords.
.SH SYNOPSIS
.B userpasswd
[
.I options
]
.SH DESCRIPTION
.B userpasswd
is a graphical tool to allow users to easily change their passwords.
Aside from being a nice GUI frontend, this program does the right
thing when the pam configuration has changed.
.SH OPTIONS
This program has no command line options of its own, but it does take
the standard X program options like
.B -display
and such.  See the 
.IR X (1)
man page for some of the common options.
.SH "SEE ALSO"
.IR userhelper (8)
.SH BUGS
No known bugs, but compatability with bizarre changes in the pam
configuration have not been tested aggressively.  If you have a
non-standard pam configuration, I'd be interested to hear whether it
worked and what kind of configuration you have.
.SH AUTHOR
Otto Hammersmith <otto@redhat.com>
